### PR TITLE
Localization for Spotify and lastfm

### PR DESCRIPTION
**Pull request by bargru**

### CODE REVIEW

**Comment by bargru** [comment]
ups was for development...

**Comment by jaedb** [comment]
Just a heads up that it's worth looking at https://github.com/jaedb/spotmop/blob/master/spotmop.php as the `$localStorage.spotify` array will be overwritten by the authentication process. I might look to nest this as `$localStorage.spotify.auth`.

**Comment by bargru** [comment]
Ah ok :) What about a new storage field just for localization?

**Comment by bargru** [comment]
The Spotify authentication process didn't ask for the scope `user-read-private`. So the Spotify API request `https://api.spotify.com/v1/me` didn't return the country of the user.

**Pull request closed without merging**
