### PR TITLE
WIP: Fix setups behind https proxy

### PR DESCRIPTION
**Pull request by johnyb**
I stumbled upon the same problem as @qurben in #53 - I configured nginx + letsencrypt as a proxy in front of mopidy http server. I basically need the following entries in the config for this to work:

```
location /pusher {
        proxy_pass http://127.0.0.1:6681/;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
}
location / {
        proxy_pass http://127.0.0.1:6680/;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
}
```

After that, in the spotmop settings pane, point everything to the webserver on port 443 (notifications port + mopidy host + port).

### CODE REVIEW

**Comment by johnyb** [comment]
I did not "build" the project, yet. I can of course just add the built files. For now, I just wanted some feedback (that's why this is WIP). If you like, I could also put some hints into the README, how to create such a setup. Or would the wiki be more suitable for such information?

I also did not test, if everything still works fine when not behind a proxy. But I don't expect any problems. Will try it, later. For now, I'm happily listening using spotmop behind https ;)

**Comment by johnyb** [comment]
seems I didn't find all urls, clicking through the complete interface, now. And even taking another look through the sources.

**Comment by johnyb** [comment]
fixed auth with spotify, I hope. Needs more extensive testing, I guess.

**Comment by jaedb** [comment]
Looks good mate, I'll run through some test cases to see if it's working at this end.

**Comment by johnyb** [comment]
Wow, that was fast ;) I wanted to double check a problem on my mobile, but I guess it's only a problem on my crude setup. I have overwritten the version on my production system with a custom build and guess I ran into some caching issue.

If there are any problems regarding this and you want me to check something, feel free to ping me. I'd be glad to help fixing any remaining issues.

**Comment by jaedb** [comment]
This doesn't work for secure websockets as these need to be configured on the server-side. This will require generation of secure certificates for the domain that you're running on (ie localhost).

In essence users wanting to use SSL will need to generate a certificate and add it to the configuration for the Mopidy and Pusher websockets to use. I would prefer to have a self-signed certificate but out of the box, self-signed certificates are denied by [most] browsers.

This would ultimately render Spotmop unusable out of the box, and for the bulk of users SSL is not required. So further work is required to make it optional. I do think it would be good practice to facilitate it for users who require it though.

I've moved this into a new branch (`feature/secure`) to contain any further work on this without interrupting the main development flow.

**Pull request merged**
